/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuildDemoRouteImport } from './routes/build-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPProgramIdRouteImport } from './routes/_app/p/$programId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const BuildDemoRoute = BuildDemoRouteImport.update({
  id: '/build-demo',
  path: '/build-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPProgramIdRoute = AppPProgramIdRouteImport.update({
  id: '/_app/p/$programId',
  path: '/p/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/build-demo': typeof BuildDemoRoute
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/p/$programId': typeof AppPProgramIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/build-demo': typeof BuildDemoRoute
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/p/$programId': typeof AppPProgramIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/build-demo': typeof BuildDemoRoute
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/p/$programId': typeof AppPProgramIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/build-demo' | '/login' | '/' | '/p/$programId' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/build-demo' | '/login' | '/' | '/p/$programId' | '/api/auth/$'
  id:
    | '__root__'
    | '/build-demo'
    | '/login'
    | '/_app/'
    | '/_app/p/$programId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BuildDemoRoute: typeof BuildDemoRoute
  LoginRoute: typeof LoginRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPProgramIdRoute: typeof AppPProgramIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/build-demo': {
      id: '/build-demo'
      path: '/build-demo'
      fullPath: '/build-demo'
      preLoaderRoute: typeof BuildDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$programId': {
      id: '/_app/p/$programId'
      path: '/p/$programId'
      fullPath: '/p/$programId'
      preLoaderRoute: typeof AppPProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BuildDemoRoute: BuildDemoRoute,
  LoginRoute: LoginRoute,
  AppIndexRoute: AppIndexRoute,
  AppPProgramIdRoute: AppPProgramIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
