/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProgramsIndexRouteImport } from './routes/_app/programs/index'
import { Route as AppProgramsProgramIdRouteImport } from './routes/_app/programs/$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgramsIndexRoute = AppProgramsIndexRouteImport.update({
  id: '/_app/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgramsProgramIdRoute = AppProgramsProgramIdRouteImport.update({
  id: '/_app/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programs/$programId': typeof AppProgramsProgramIdRoute
  '/programs/': typeof AppProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programs/$programId': typeof AppProgramsProgramIdRoute
  '/programs': typeof AppProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app/programs/$programId': typeof AppProgramsProgramIdRoute
  '/_app/programs/': typeof AppProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programs/$programId' | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programs/$programId' | '/programs'
  id: '__root__' | '/' | '/_app/programs/$programId' | '/_app/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppProgramsProgramIdRoute: typeof AppProgramsProgramIdRoute
  AppProgramsIndexRoute: typeof AppProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/programs/': {
      id: '/_app/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof AppProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/programs/$programId': {
      id: '/_app/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AppProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppProgramsProgramIdRoute: AppProgramsProgramIdRoute,
  AppProgramsIndexRoute: AppProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
